# Generated by Django 3.1.7 on 2021-05-26 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oligos', '0002_auto_20210425_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oligo',
            options={'ordering': ['-created_date']},
        ),
        migrations.RenameField(
            model_name='oligo',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
