# Generated by Django 3.1.6 on 2021-02-14 19:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oligos', '0002_auto_20191010_2226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oligo',
            options={'ordering': ['create_date']},
        ),
        migrations.AlterField(
            model_name='oligo',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='oligo',
            name='name',
            field=models.CharField(max_length=65, unique=True),
        ),
        migrations.AlterField(
            model_name='oligo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserMap',
        ),
    ]
