# Generated by Django 3.1.7 on 2021-02-21 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oligos', '0003_auto_20210214_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oligo',
            options={'ordering': ['-create_date']},
        ),
        migrations.AddField(
            model_name='oligo',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oligos', to=settings.AUTH_USER_MODEL),
        ),
    ]
